applications/payments/urls.py
from django.conf.urls import url

from .views import payments
from .ajax import transaction

urlpatterns = [
    url(r'^$', payments, name='payments'),
]

urlpatterns += [
    url(r'^transaction/$', transaction, name='transaction'),

]

benovate_testapp/urls.py
"""
benovate_testapp URL Configuration
"""

from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^payments/', include('applications.payments.urls')),
    url(r'^select2/', include('django_select2.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/accounts/models.py
# coding:utf-8
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class User(AbstractUser):
    inn = models.CharField(
        verbose_name='ИНН', max_length=12,
        validators=[RegexValidator(
            regex='^\d{10,12}$', message="Введите правильный ИНН"
        )]
    )
    score = models.DecimalField(
        'Счет', max_digits=9, decimal_places=2, default=0
    )

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

applications/payments/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

applications/payments/forms.py
# coding:utf-8
from __future__ import unicode_literals

from django import forms
from django.core.validators import RegexValidator

from django_select2.forms import ModelSelect2Widget

from applications.accounts.models import User


class PaymentForm(forms.Form):
    user = forms.IntegerField(
        widget=ModelSelect2Widget(
            attrs={'data-placeholder': 'Введите имя пользователя'},
            model=User,
            search_fields=['username__istartswith']
        )
    )
    inn = forms.CharField(
        validators=[RegexValidator(
            regex='^\d{10,12}$', message="Введите правильный ИНН"
        )]
    )
    score = forms.DecimalField(max_digits=9, decimal_places=2)

    def clean_inn(self):
        inn = self.cleaned_data.get('inn')
        user_id = self.cleaned_data.get('user')
        users = User.objects.filter(inn=inn).exclude(id=user_id)
        if users:
            return inn
        else:
            raise forms.ValidationError("Пользователи с таким ИНН не найдены")

    def clean_score(self):
        score = self.cleaned_data.get('score')
        user_id = self.cleaned_data.get('user')
        user = User.objects.get(id=user_id)
        if score < 0:
            raise forms.ValidationError("Введите положительную сумму")
        if user.score >= score:
            return score
        else:
            raise forms.ValidationError(
                "Указанная сумма превышает баланс пользователя"
            )

applications/accounts/views.py
from django.shortcuts import render

# Create your views here.

applications/payments/views.py
# coding:utf-8
from __future__ import unicode_literals

from django.shortcuts import render

from .forms import PaymentForm


def payments(request):
    form = PaymentForm(request.POST or None)
    return render(request, 'payments/payment.html', {"form": form})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
  <head>

    <title></title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=yes">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    {% block css %}{% endblock %}

    <script src="{% static 'vendor/jquery-1.12.3.min.js' %}"></script>
  </head>

  <body>
    <div class="container">
      <div class="row">
          <div class="col-lg-12">{% block content %}{% endblock %}</div>
      </div>
    </div>


    <script src="{% static 'vendor/jquery.form.min.js' %}"></script>
    <script src="{% static 'js/cleanForms.js' %}"></script>
    {% block js_bottom %}{% endblock %}
  </body>
</html>

templates/payments/payment.html
{% extends "base.html" %}
{% load static %}

{% block css %}
  {{ form.media.css }}
  <link rel="stylesheet" href="{% static 'css/select2.css' %}">
  <link rel="stylesheet" href="{% static 'css/payment.css' %}">
{% endblock %}

{% block content %}
<form id="payment_form" role="form" method="post" action="{% url 'transaction' %}" class="form-horizontal">
  {% csrf_token %}
  <p class="success"></p>
  <div class="form-group">
    <label for="id_user" class="control-label col-lg-2 sr-only">Пользователь:</label>
    <div class="col-lg-8">
        <div class="input-group">
            <div class="input-group-addon"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;</div>
            {{ form.user }}
        </div>
        <div class="error"></div>
    </div>
  </div>
  <div class="form-group" >
      <label for="id_inn" class="control-label col-lg-2 sr-only">ИНН:</label>
      <div class="col-lg-8">
          <div class="input-group">
              <div class="input-group-addon"><span class="glyphicon glyphicon-file" aria-hidden="true"></span>&nbsp;</div>
              <input type="text" class="form-control" name="inn" id="id_inn"
              placeholder="Введите ИНН">
          </div>
          <div class="error"></div>
      </div>
  </div>
  <div class="form-group" >
      <label for="id_score" class="control-label col-lg-2 sr-only">Сумма:</label>
      <div class="col-lg-8">
          <div class="input-group">
              <div class="input-group-addon"><span class="glyphicon glyphicon-ruble" aria-hidden="true"></span>&nbsp;</div>
              <input type="number" step="0.01" class="form-control" name="score" id="id_score"
              placeholder="Введите сумму для перевода">
          </div>
          <div class="error"></div>
      </div>
  </div>
  <a class="btn btn-primary js-submit">Перевести</a>
</form>

{% endblock %}

{% block js_bottom %}
  {{ form.media.js }}
{% endblock %}